# Generated by Django 5.2.13 on 2026-05-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ONBOARDING', 'Onboarding')], default='ONBOARDING', max_length=20)),
                ('service_state', models.CharField(blank=True, max_length=2)),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=64)),
                ('telegram_user_id', models.CharField(blank=True, max_length=64)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('telegram_group_chat_id', models.CharField(blank=True, max_length=64)),
                ('google_calendar_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'display_name'],
            },
        ),
    ]
