# Generated by Django 5.2.13 on 2026-05-02 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianTelegramRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('LINKED', 'Linked'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=20)),
                ('telegram_user_id', models.CharField(blank=True, max_length=64)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('telegram_group_chat_id', models.CharField(blank=True, max_length=64)),
                ('telegram_group_title', models.CharField(blank=True, max_length=255)),
                ('telegram_chat_type', models.CharField(blank=True, max_length=32)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_registrations', to='technicians.technician')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['technician', 'status'], name='technicians_technic_38c5a9_idx'), models.Index(fields=['telegram_user_id', 'status'], name='technicians_telegra_64a1dc_idx')],
            },
        ),
    ]
