# Generated by Django 5.2.13 on 2026-05-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_sync', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SENT', 'Sent'), ('SIGNED', 'Signed'), ('CANCELED', 'Canceled'), ('ERROR', 'Error')], default='DRAFT', max_length=20)),
                ('contract_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('contract_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField()),
                ('customer_phone', models.CharField(max_length=32)),
                ('state_id', models.CharField(blank=True, max_length=64)),
                ('project_type', models.CharField(choices=[('AIR_DUCT_CLEANING', 'Air Duct Cleaning'), ('DRYER_VENT_CLEANING', 'Dryer Vent Cleaning'), ('CHIMNEY_CLEANING', 'Chimney Cleaning'), ('HVAC_MAINTENANCE', 'HVAC Maintenance'), ('OTHER', 'Other')], max_length=32)),
                ('project_description', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_date', models.CharField(blank=True, max_length=10)),
                ('billing_zip_code', models.CharField(blank=True, max_length=16)),
                ('submitted_by_telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('submitted_from_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('pdf_file_url', models.URLField(blank=True)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('raw_submission', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_contracts', to='calendar_sync.calendarevent')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contracts', to='technicians.technician')),
            ],
            options={
                'ordering': ['-contract_date', '-created_at'],
                'indexes': [models.Index(fields=['technician', 'contract_date'], name='contracts_s_technic_418979_idx'), models.Index(fields=['calendar_event'], name='contracts_s_calenda_a1096c_idx'), models.Index(fields=['status'], name='contracts_s_status_e1d23c_idx'), models.Index(fields=['contract_number'], name='contracts_s_contrac_4de14f_idx'), models.Index(fields=['created_at'], name='contracts_s_created_14bc99_idx')],
            },
        ),
    ]
