# Generated by Django 5.2.13 on 2026-05-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontract',
            name='payment_processing_type',
            field=models.CharField(blank=True, choices=[('SWIPED', 'Swiped'), ('MANUALLY_ENTERED', 'Manually Entered'), ('OVER_THE_PHONE', 'Over-the-phone')], max_length=32),
        ),
    ]
