# Generated by Django 5.2.13 on 2026-05-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_sync', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('expense_type', models.CharField(choices=[('GAS', 'Gas'), ('MATERIALS', 'Materials'), ('PARKING', 'Parking'), ('TOLL', 'Toll'), ('TOOL', 'Tool'), ('PARTS', 'Parts'), ('SUPPLIES', 'Supplies'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('receipt_photo_url', models.URLField(blank=True)),
                ('submitted_by_telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('submitted_from_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('raw_submission', models.JSONField(blank=True, default=dict)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_reports', to='calendar_sync.calendarevent')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='technicians.technician')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['technician', 'expense_date'], name='expenses_ex_technic_daefd4_idx'), models.Index(fields=['calendar_event'], name='expenses_ex_calenda_5f7989_idx'), models.Index(fields=['expense_type'], name='expenses_ex_expense_547895_idx'), models.Index(fields=['created_at'], name='expenses_ex_created_0cd667_idx')],
            },
        ),
    ]
