# Generated by Django 5.2.13 on 2026-05-01 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(max_length=255)),
                ('google_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('JOB', 'Job'), ('PERSONAL_BLOCK', 'Personal Block'), ('INTERNAL_BLOCK', 'Internal Block'), ('OTHER', 'Other')], default='JOB', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled'), ('FAKE', 'Fake'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=64)),
                ('job_number', models.CharField(blank=True, max_length=64, null=True)),
                ('is_report_required', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_google_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='technicians.technician')),
            ],
            options={
                'ordering': ['start_at', 'technician__last_name', 'technician__first_name'],
                'indexes': [models.Index(fields=['technician', 'start_at'], name='calendar_sy_technic_305d22_idx'), models.Index(fields=['status'], name='calendar_sy_status_06e5a3_idx'), models.Index(fields=['event_type'], name='calendar_sy_event_t_3ffbda_idx'), models.Index(fields=['google_event_id'], name='calendar_sy_google__ebfa44_idx')],
                'constraints': [models.UniqueConstraint(fields=('google_calendar_id', 'google_event_id'), name='unique_google_calendar_event')],
            },
        ),
    ]
