# Generated by Django 5.2.13 on 2026-05-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_sync', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('job_number', models.CharField(blank=True, max_length=64)),
                ('building_number', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('ZELLE', 'Zelle'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('FINANCING', 'Financing'), ('GROUPON', 'Groupon'), ('ESTIMATE', 'Estimate'), ('CANCEL', 'Cancel'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closed_by', models.CharField(choices=[('TECHNICIAN', 'Technician'), ('MANAGER', 'Manager'), ('CALL_CENTER', 'Call Center'), ('CUSTOMER', 'Customer'), ('OTHER', 'Other')], max_length=20)),
                ('project_description', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('groupon_review', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('N_A', 'N/A')], default='N_A', max_length=10)),
                ('google_review', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('N_A', 'N/A')], default='N_A', max_length=10)),
                ('yearly_maintenance_plan', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('N_A', 'N/A')], default='N_A', max_length=10)),
                ('submitted_by_telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('submitted_from_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('raw_submission', models.JSONField(blank=True, default=dict)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('calendar_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_reports', to='calendar_sync.calendarevent')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='technicians.technician')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['technician', 'report_date'], name='reports_wor_technic_eedd3b_idx'), models.Index(fields=['calendar_event'], name='reports_wor_calenda_0cb422_idx'), models.Index(fields=['payment_type'], name='reports_wor_payment_20a6e9_idx'), models.Index(fields=['created_at'], name='reports_wor_created_91811a_idx')],
            },
        ),
    ]
